# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e32faf19370faa51b4c3f6e8f5ab151e2f559c5b210cee8e4161d843378217c72322df49596fc7ad49f5549fc79387745060ef857bab96198c96084a5a3ceb77

test:
  secret_key_base: b182a3008fc94655bdbbc92638bbd5406ca79ec3c33a80ea23e99f1f6c1ebf9b84a011d1a3d81a704076b4bac9192471f8c4eddc45f94cf51e931baa6986df84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
